version: '3.5'
services:
  db: # Banco de dados
    hostname: db
    image: postgres
    command: postgres -c log_min_messages=FATAL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Products
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql postgres